import json
import os

languages = ["en", "ar", "de", "es", "fr", "ru", "ko", "pt", "zh", "ja"]

# Define the structure and keys
structure = {
    "common.json": ["app.name", "app.tagline", "common.cancel", "common.save", "common.delete", "common.edit", "common.close", "common.ok", "common.retry", "common.loading", "common.error", "common.success", "common.warning", "common.info", "common.copy", "common.paste", "common.search", "common.clear", "common.refresh", "common.add", "common.remove", "common.back", "common.next", "common.done", "common.empty", "common.new", "system.cpu", "system.memory", "system.disk", "system.network", "system.uptime", "system.hostname"],
    "workspace.json": ["workspace.newSession", "workspace.sessions", "workspace.sshServers", "workspace.noSessions", "workspace.createSession", "sidebar.sessions", "sidebar.ssh", "sidebar.git", "sidebar.docker", "sidebar.ai", "sidebar.quickFix", "sidebar.explain", "sidebar.generate", "sidebar.debug", "sidebar.settings", "sidebar.shortcuts", "commandBar.title", "commandBar.placeholder", "commandBar.commands", "commandBar.servers", "commandBar.files", "commandBar.askAI", "session.tab.local", "session.tab.ssh", "session.tab.close", "session.tab.duplicate", "session.tab.rename"],
    "settings.json": ["settings.title", "settings.general", "settings.theme", "settings.language", "settings.ssh", "settings.ai", "settings.about", "settings.close", "general.title", "general.subtitle", "general.interface", "general.autoOpenHistory", "general.autoOpenHistoryDesc", "general.autoOpenAI", "general.autoOpenAIDesc", "general.terminalFeatures", "general.interactiveOutput", "general.interactiveOutputDesc", "general.deepFileParsing", "general.deepFileParsingDesc", "general.autoLSafterCD", "general.autoLSafterCDDesc", "language.title", "language.subtitle", "language.current", "language.available", "language.restartNote", "theme.title", "theme.subtitle", "theme.appearance", "theme.dark", "theme.light", "theme.system", "theme.accentColor", "theme.font", "theme.fontSize", "ai.title", "ai.subtitle", "ai.apiKey", "ai.model", "ai.enabled", "ai.contextLength", "about.title", "about.version", "about.build", "about.developer", "about.website", "about.github", "about.support", "about.privacy", "about.terms", "about.acknowledgments", "shortcuts.title", "shortcuts.addNew", "shortcuts.category", "shortcuts.icon", "shortcuts.color", "shortcuts.shortcut", "shortcuts.command", "shortcuts.description", "shortcuts.save"],
    "terminal.json": ["terminal.execute", "terminal.clear", "terminal.interrupt", "terminal.typeCommand", "terminal.running", "terminal.completed", "terminal.failed", "terminal.exitCode"],
    "intelligence.json": ["intelligence.title", "intelligence.chat", "intelligence.files", "intelligence.history", "intelligence.errors", "intelligence.suggestions", "intelligence.scripts", "chat.askAnything", "chat.helpMessage", "chat.typingPlaceholder", "chat.send", "chat.thinking", "chat.copyCode", "chat.runCode", "files.title", "files.scanning", "files.emptyFolder", "files.unableToList", "files.verifySSH", "files.retryConnection", "files.noItems", "files.open", "files.edit", "files.download", "files.upload", "files.copyPath", "files.showInFinder", "files.delete", "files.newFile", "files.newFolder", "history.title", "history.noHistory", "history.runAgain", "history.copyCommand", "history.clearHistory", "history.searchPlaceholder", "errors.title", "errors.noErrors", "errors.explain", "errors.fix", "errors.dismiss", "suggestions.title", "suggestions.noSuggestions", "suggestions.basedOn", "scripts.title", "scripts.noScripts", "scripts.run", "scripts.edit", "scripts.delete", "scripts.create"],
    "ssh.json": ["ssh.title", "ssh.subtitle", "ssh.addServer", "ssh.editServer", "ssh.deleteServer", "ssh.serverName", "ssh.host", "ssh.port", "ssh.username", "ssh.password", "ssh.privateKey", "ssh.connect", "ssh.disconnect", "ssh.connecting", "ssh.connected", "ssh.connectionFailed", "ssh.enterPassword", "ssh.noServers", "ssh.addFirstServer"],
    "git.json": ["git.sourceControl", "git.syncChanges", "git.clean", "git.sync", "git.staged", "git.modified", "git.untracked", "git.commitMessage", "git.suggest", "git.commitTo", "git.noChanges", "git.pull", "git.push", "git.fetch", "git.branch", "git.stash"],
    "docker.json": ["docker.title", "docker.containers", "docker.images", "docker.volumes", "docker.networks", "docker.running", "docker.stopped", "docker.start", "docker.stop", "docker.restart", "docker.remove", "docker.logs", "docker.exec", "docker.noContainers", "docker.notRunning"],
    "editor.json": ["editor.title", "editor.save", "editor.saveAs", "editor.undo", "editor.redo", "editor.find", "editor.replace", "editor.lineNumbers", "editor.wordWrap", "editor.unsavedChanges", "editor.discardChanges", "editor.fetchingFile", "editor.saving", "editor.saved", "editor.saveFailed"]
}

# (I will now add the translation data for all languages in bits to manage the file size)
